# Form implementation generated from reading ui file 'MarkerScanUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MarkerScan(object):
    def setupUi(self, MarkerScan):
        MarkerScan.setObjectName("MarkerScan")
        MarkerScan.resize(1024, 720)
        MarkerScan.setMinimumSize(QtCore.QSize(1024, 720))
        MarkerScan.setMaximumSize(QtCore.QSize(1024, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MarkerScan.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=MarkerScan)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 720))
        self.label.setMinimumSize(QtCore.QSize(1024, 720))
        self.label.setMaximumSize(QtCore.QSize(1024, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/BackGround.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=MarkerScan)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1031, 721))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 395, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 8)
        spacerItem1 = QtWidgets.QSpacerItem(265, 10, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(255, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 7, 1, 1)
        self.runButton = QtWidgets.QToolButton(parent=self.gridLayoutWidget)
        self.runButton.setMinimumSize(QtCore.QSize(155, 155))
        self.runButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.runButton.setStyleSheet("QToolButton {\n"
"background: rgba(0,0,0,0);\n"
"}\n"
"QToolButton:hover {\n"
"border: 8px solid #000;\n"
"border-radius: 40px;\n"
"}")
        self.runButton.setText("")
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 3, 1, 1, 1)
        self.circleMode = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.circleMode.setFont(font)
        self.circleMode.setObjectName("circleMode")
        self.gridLayout.addWidget(self.circleMode, 3, 3, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.picButton = QtWidgets.QToolButton(parent=self.gridLayoutWidget)
        self.picButton.setMinimumSize(QtCore.QSize(155, 150))
        self.picButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.picButton.setStyleSheet("QToolButton {\n"
"background: rgba(0,0,0,0);\n"
"}\n"
"QToolButton:hover {\n"
"border: 8px solid #000;\n"
"border-radius: 40px;\n"
"}")
        self.picButton.setText("")
        self.picButton.setObjectName("picButton")
        self.gridLayout.addWidget(self.picButton, 3, 6, 1, 1)
        self.errorLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.errorLabel.sizePolicy().hasHeightForWidth())
        self.errorLabel.setSizePolicy(sizePolicy)
        self.errorLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("color: #f00;")
        self.errorLabel.setText("")
        self.errorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.gridLayout.addWidget(self.errorLabel, 1, 1, 1, 6)
        self.lineMode = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.lineMode.setFont(font)
        self.lineMode.setObjectName("lineMode")
        self.gridLayout.addWidget(self.lineMode, 3, 4, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 6)

        self.retranslateUi(MarkerScan)
        QtCore.QMetaObject.connectSlotsByName(MarkerScan)

    def retranslateUi(self, MarkerScan):
        _translate = QtCore.QCoreApplication.translate
        MarkerScan.setWindowTitle(_translate("MarkerScan", "МаркерСкан"))
        self.circleMode.setText(_translate("MarkerScan", "Точки"))
        self.lineMode.setText(_translate("MarkerScan", "Линии"))
